CREATE TABLE COLABORADOR(
    CODIGO VARCHAR2(50),
    NOME VARCHAR2(50),
    AREA VARCHAR2(50),
    NOTA NUMBER(3,1),
    CONSTRAINT PK_COLABORADOR PRIMARY KEY (CODIGO)
);
CREATE TABLE INDICADOR(
    ID VARCHAR2(50),
    NOME VARCHAR2(50),
    PESO NUMBER(2, 1),
    UNIDADE VARCHAR2(50),
    META NUMBER(7,2),
    SUPERMETA NUMBER(7,2),
    DESAFIO NUMBER(7,2),
    MES NUMBER(2),
    CONSTRAINT PK_INDICADOR PRIMARY KEY (ID)
);
CREATE TABLE FAZER(
    CODIGO VARCHAR2(50),
    ID VARCHAR2(50),
    PROGRESSO NUMBER(7,2) DEFAULT 0,
    FEITO NUMBER(1) DEFAULT 0,
    CONSTRAINT PK_FAZER PRIMARY KEY (CODIGO, ID),
    CONSTRAINT FK_COLABORADOR_FAZ FOREIGN KEY (CODIGO) REFERENCES COLABORADOR,
    CONSTRAINT FK_INDICADOR_FAZ FOREIGN KEY (ID) REFERENCES INDICADOR
);